# Generated by Django 2.1.5 on 2019-02-14 20:20

from django.db import migrations, models
import zwazo.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sound_file',
            field=models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
    ]
