# Generated by Django 2.1.7 on 2019-02-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_sound_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('yes_no', 'Yes/No')], max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Language')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='numeric_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeric_surveys', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='survey',
            name='text_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_surveys', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='survey',
            name='yes_no_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yes_no_surveys', to='surveys.Prompt'),
        ),
    ]
