# Generated by Django 2.1.7 on 2019-02-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_prompt_sound_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Language'),
        ),
        migrations.AddField(
            model_name='survey',
            name='prompt_type',
            field=models.CharField(choices=[('default', 'Default Prompts'), ('text', 'Custom Text'), ('sound', 'Custom Sound'), ('none', 'No Prompts')], default='default', max_length=50),
        ),
    ]
