# Generated by Django 2.1.7 on 2019-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20190215_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('voice', 'Voice'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='voice', max_length=30),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('yes_no', 'Yes/No'), ('welcome', 'Welcome')], max_length=50),
        ),
    ]
