# Generated by Django 2.1.7 on 2019-02-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20190221_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='welcome_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_surveys', to='surveys.Prompt'),
        ),
    ]
