# Generated by Django 2.1.7 on 2019-02-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_welcome_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Contact'),
        ),
    ]
