# Generated by Django 2.1.7 on 2019-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20190222_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('yes_no', 'Yes or no'), ('numeric', 'Numeric')], default='yes_no', max_length=255),
        ),
    ]
