# Generated by Django 2.1.7 on 2019-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20190222_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
