# Generated by Django 2.1.7 on 2019-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('project', 'phone')},
        ),
    ]
