# Generated by Django 2.1.7 on 2019-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20190222_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(choices=[('none', 'None'), ('oneway', 'One-Way'), ('twoway', 'Two-Way')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='sms',
            field=models.CharField(choices=[('none', 'None'), ('oneway', 'One-Way'), ('twoway', 'Two-Way')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='voice',
            field=models.CharField(choices=[('none', 'None'), ('oneway', 'One-Way'), ('twoway', 'Two-Way')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp',
            field=models.CharField(choices=[('none', 'None'), ('oneway', 'One-Way'), ('twoway', 'Two-Way')], default='none', max_length=20),
        ),
    ]
