# Generated by Django 2.1.7 on 2019-03-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_auto_20190311_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_prompt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(default=1),
        ),
    ]
