# Generated by Django 2.1.7 on 2019-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20190311_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='response',
            field=models.CharField(max_length=255),
        ),
    ]
