# Generated by Django 2.2.10 on 2020-12-01 21:51

from django.db import migrations, models
import django.db.models.deletion
import zwazo.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20190311_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rewinder',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('is_global', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question')),
                ('redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects', to='surveys.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('sound_file', models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Survey')),
            ],
        ),
    ]
