# Generated by Django 2.1.5 on 2019-08-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('broadcast_type', models.CharField(choices=[('voice', 'Voice'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='voice', max_length=30)),
                ('prompt_type', models.CharField(choices=[('default', 'Default Prompts'), ('text', 'Custom Text'), ('sound', 'Custom Sound'), ('none', 'No Prompts')], default='default', max_length=50)),
            ],
        ),
    ]
