# Generated by Django 2.1.5 on 2019-08-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='goodbye_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goodbye_broadcasts', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Language'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='numeric_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeric_broadcasts', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Project'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='respondents',
            field=models.ManyToManyField(blank=True, to='surveys.Contact'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='text_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_broadcastes', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='welcome_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_broadcasts', to='surveys.Prompt'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='yes_no_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yes_no_broadcasts', to='surveys.Prompt'),
        ),
    ]
