# Generated by Django 2.1.5 on 2019-08-26 21:17

from django.db import migrations, models
import django.db.models.deletion
import zwazo.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('broadcasts', '0002_auto_20190826_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('yes_no', 'Yes/No'), ('welcome', 'Welcome'), ('goodbye', 'Goodbye')], max_length=50)),
                ('sound_file', models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/')),
                ('is_default', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_languages', to='surveys.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('yes_no', 'Yes or no'), ('numeric', 'Numeric')], default='yes_no', max_length=255)),
                ('sound', models.CharField(blank=True, max_length=255)),
                ('sound_file', models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/')),
                ('repeater', models.CharField(blank=True, max_length=2)),
                ('terminator', models.CharField(blank=True, max_length=2)),
                ('max_length', models.IntegerField(default=1)),
                ('timeout', models.IntegerField(default=5)),
                ('has_prompt', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('transcription', models.TextField(blank=True)),
                ('call_sid', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_question_response', to='surveys.Contact')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcasts.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='goodbye_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goodbye_broadcasts', to='broadcasts.Prompt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='numeric_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeric_broadcasts', to='broadcasts.Prompt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='text_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_broadcastes', to='broadcasts.Prompt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='welcome_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_broadcasts', to='broadcasts.Prompt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='yes_no_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yes_no_broadcasts', to='broadcasts.Prompt'),
        ),
        migrations.AddField(
            model_name='question',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcasts.Broadcast'),
        ),
    ]
