# Generated by Django 2.1.5 on 2019-08-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_auto_20190826_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_site.Language'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_site.Project'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='respondents',
            field=models.ManyToManyField(blank=True, to='base_site.Contact'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_languages', to='base_site.Language'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_question_response', to='base_site.Contact'),
        ),
    ]
