# Generated by Django 2.1.5 on 2019-08-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0006_auto_20190828_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_callback',
            field=models.BooleanField(default=False),
        ),
    ]
