# Generated by Django 2.1.5 on 2019-08-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0007_broadcast_is_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Text', 'Text'), ('Sound', 'Sound')], max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('repeater', models.CharField(blank=True, max_length=2)),
                ('response', models.CharField(blank=True, max_length=2)),
                ('max_length', models.IntegerField(default=1)),
                ('timeout', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='broadcast',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='goodbye_prompt',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='numeric_prompt',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='prompt_type',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='text_prompt',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='welcome_prompt',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='yes_no_prompt',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcasts.Broadcast'),
        ),
    ]
