# Generated by Django 2.1.5 on 2019-08-30 17:44

from django.db import migrations, models
import zwazo.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0008_auto_20190830_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='sound_file',
            field=models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
    ]
