# Generated by Django 2.1.5 on 2019-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0009_broadcastmessage_sound_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
