# Generated by Django 2.1.5 on 2019-08-30 21:20

from django.db import migrations, models
import zwazo.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0010_broadcastmessage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='broadcast',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='max_length',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='repeater',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='response',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='sound_file',
            field=models.FileField(blank=True, null=True, storage=zwazo.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
    ]
